version: '2'
services:
    codefestmanagementsystemv1-app:
        image: codefestmanagementsystemv1
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://codefestmanagementsystemv1-mysql:3306/codefestmanagementsystemv1?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=codefestmanagementsystemv1-elasticsearch:9300
        ports:
            - 8080:8080
    codefestmanagementsystemv1-mysql:
        extends:
            file: mysql.yml
            service: codefestmanagementsystemv1-mysql
    codefestmanagementsystemv1-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: codefestmanagementsystemv1-elasticsearch
